name: "📊 Ghent postzegelbosjes report"

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 12 * * 1-5"

jobs:
  report:
    name: "📊 Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "📫 Checkout"
        uses: actions/checkout@v2
      - name: "🧱 Setup Ruby"
        uses: ruby/setup-ruby@v1.90.0
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: "📊 Scan"
        id: scan
        run: |
          REPORT=$(bin/scan --no-progress)
          echo $REPORT
          REPORT="${REPORT//'%'/'%25'}"
          REPORT="${REPORT//$'\n'/'%0A'}"
          REPORT="${REPORT//$'\r'/'%0D'}"
          echo "::set-output name=report::$REPORT"
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          from: Postzegelbos Scanner
          to:  ${{secrets.MAIL_TO}}
          subject: Postzegelbos report - Ghent
          body: "${{ steps.scan.outputs.report }}"
          convert_markdown: true
